version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    groups:
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      prod-dependencies:
        dependency-type: "production"
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    groups:
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      prod-dependencies:
        dependency-type: "production"
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    groups:
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
      prod-dependencies:
        dependency-type: "production"
        patterns:
          - "*"
